### ISSUE TITLE
Specify the log level per crate

### ISSUE THREAD

**Issue by piegamesde** [borntyping/rust-simple_logger#15]
This is an important feature to me, because my log is cluttered with `trace`s from dependencies. All other crates that have this feature are just a pain to set up.

**Comment by creekorful** [comment]
I have face the same issue as @piegamesde and totally agree with him, 
I can manage the PR if you want. What do you think @borntyping ?

**Comment by borntyping** [comment]
I'll happily accept an MR to implement something for this - ideally something as simple as possible though :)
