### ISSUE TITLE
How to specify output file

### ISSUE THREAD

**Issue by LovaTahina** [borntyping/rust-simple_logger#16]
Hello,
Could you just show how to output into file?
Regards

**Comment by 3NdR1m** [comment]
Hi. From what I understand, the logger simply output to stderr and stdout. It's then up to whatever program called your application to redirect the output.
On linux:
Redirect stdout:
`app >> out`

Redirect stdout and stderr:
`app &> out`

Where `app` is either `cargo run` or your app's binary, and out is the output file/program/device.

If the output is not specified, it simply spit out to CLI.
