### ISSUE TITLE
Wildcard for `with_module_level`

### ISSUE THREAD

**Issue by piegamesde** [borntyping/rust-simple_logger#24]
I've now updated my code to #20 and its a great improvement! However, the list of modules for which I call `with_module_level` is rather long and keeps growing. I also tried whitelisting instead of blacklisting but this merely flips the problem upside down.

Some kind of wildcard semantics where I can set the log level for a module + all submodules would reduce the amount of `with_module_level` calls to just 3 (and to 1 with whitelisting).

I can think of a few possibilities for a possible API:

- Make a module level filter automatically match all submodules as well
- Add \* glob parsing
- Add a new method that has a "this module and all submodules" semantic

(I prefer the first one)

**Comment by creekorful** [comment]
Hello there! 

I was facing the same problem and AFAIC your first proposition is definitely the best one 👍🏻
