### ISSUE TITLE
How to flush the logger.

### ISSUE THREAD

**Issue by sedrik** [borntyping/rust-simple_logger#33]
I am trying to setup a AWS Lambda where I wanted to use simple_logger as my logging facility but it seems that I need to flush the logger before the lambda shutsdown otherwise I will get buffered but not yet written messages printed in the lamda logs.

The log::Log trait does expose a flush method but as init only returns a unit value I do not have access to the flogger to call flush on it.

Is this an oversight or should I look for a different library for my logging needs?

**Comment by piegamesde** [comment]
I'd say this is an oversight: https://github.com/borntyping/rust-simple_logger/blob/master/src/lib.rs#L233

As this logger only writes to `stdout`, I think you can work around this by flushing it instead.

**Comment by sedrik** [comment]
Yeah worked around it by flushing stdout. If possible flushing on Drop might be a decent solution?

**Comment by borntyping** [comment]
The `Log` trait now has a `flush()` method. It's been a while, but hopefully this fixes your issue if it's still a problem.

```rust
use simple_logger::SimpleLogger;

fn main() {
    SimpleLogger::new().init().unwrap();

    log::warn!("This is an example message.");

    log::logger().flush();
}
```

https://github.com/borntyping/rust-simple_logger/commit/80c236b7aa39b09e9f6bf3c5df056025456b5f78

**Comment by sedrik** [comment]
Thanks I have been using the workaround to flush stdout but will switch over to this the next time I need to update the lambda in question. :)
