### ISSUE TITLE
Feature Request: Allow specifying a custom UTC offset for timestamps

### ISSUE THREAD

**Issue by msrd0** [borntyping/rust-simple_logger#50]
This makes it possible to use the logger with local timestamps in multi-threadded applications that only run for a short duration, so switching between timezones (e.g. due to daylight saving stuff) wouldn't be an issue.

**Comment by borntyping** [comment]
I think this should be reasonably easy to add? I'll take a look when I have some time.

**Comment by borntyping** [comment]
An option to use a static UTC offset has been included in [simple_logger 2.0.0](https://github.com/borntyping/rust-simple_logger/releases/tag/v2.0.0).

**Comment by msrd0** [comment]
Thank you for implementing this feature.

Is it possible to have a constant width timestamp with version 2.0.0? With version 1.16.0 all messages were perfectly aligned, as there were always 3 decimal places of the second printed, but now I see varying length of decimal places which makes the rest of the log become unaligned.

**Comment by borntyping** [comment]
Oh, that's really annoying. I'll take a look tommorow.

I've seen similar issues in other languages before where values like `.100` get shortened to `.1`.
