### ISSUE TITLE
`must_use` on SimpleLogger methods

### ISSUE THREAD

**Issue by DesmondWillowbrook** [borntyping/rust-simple_logger#60]
Placing `#[must_use]` on most methods on `SimpleLogger` would help remind users to use `init` to actually initialize the logger.

I'd be happy to work on this as well.

**Comment by borntyping** [comment]
I'd be very happy to accept an MR adding this :)

**Comment by DesmondWillowbrook** [comment]
It seems that #25 has dealt with this already. Huh, I could've sworn that I didn't see any warnings when using the crate, but testing it now seems to work.
