### ISSUE TITLE
`SimpleLogger::env` doesn't (fully) simulate `env_logger`

### ISSUE THREAD

**Issue by d4h0** [borntyping/rust-simple_logger#75]
The docs of [SimpleLogger::env](https://docs.rs/simple_logger/latest/simple_logger/struct.SimpleLogger.html#method.env) say "Simulates env_logger behavior", but this doesn't seem to be true.

The docs of `env_logger` [mention](https://docs.rs/env_logger/latest/env_logger/#enabling-logging) "Logging is controlled via the RUST_LOG environment variable. The value of this environment variable is a comma-separated list of logging directives.", but comma-seperated logging directives are not supported in `simple_logger`:

```rust
    pub fn env(mut self) -> SimpleLogger {
        self.default_level = std::env::var("RUST_LOG")
            .ok()
            .as_deref()
            .map(log::LevelFilter::from_str)
            .and_then(Result::ok)
            .unwrap_or(self.default_level);

        self
    }
```

PS: Thanks for creating `simple_logger`. I like it quite a lot, and use it for all projects for which the `tracing` crate would be over-kill.

**Comment by borntyping** [comment]
A PR to update this would be welcome - only the `RUST_LOG=info` style is supported. (There are no plans to add the same filtering capabilities as `env_logger` provides.)

**Comment by icecamphor** [comment]
[SimpleLogger::with_module_level](https://docs.rs/simple_logger/4.3.0/simple_logger/struct.SimpleLogger.html#method.with_module_level) already exists, adding support for `RUST_LOG` based filtering seems trivial

why is not planned ?

**Comment by borntyping** [comment]
I added a notice to the project recently that covers this: https://github.com/borntyping/rust-simple_logger#project-status

In short - no features have been planned for this library for the better part of a decade. I keep up with bugfixes and merge contributed features that fit the project's goal of being simple, but I'm not interested in doing much more than that as I don't use the project myself.

If there's truely a trivial implementation for this, I'd welcome a pull request :)

**Comment by icecamphor** [comment]
i don't know if the code is simple enough but i created #89 anyway
