### ISSUE TITLE
Build error on WebAsssembly

### ISSUE THREAD

**Issue by riidefi** [borntyping/rust-simple_logger#82]
Please update your time dependency

https://github.com/time-rs/time/blob/main/CHANGELOG.md#fixed-5
https://github.com/time-rs/time/blob/main/CHANGELOG.md#0313-2022-08-09

**Comment by borntyping** [comment]
`simple_logger`'s dependencies should allow you to upgrade to `time` 0.3.18. It depends on `^0.3.16` which expands to `>= 0.3.16, < 0.4.0` [[1](https://github.com/borntyping/rust-simple_logger/blob/main/Cargo.toml#L20C21-L20C22)].

I've not used cargo in a while, but I belive `cargo update` should upgrade `time` and failing that I would try `cargo update --package simple_logger --aggressive` to specifically instruct it to upgrade `simple_logger`'s dependencies.
